src/Entity/AllocatedTopic.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AllocatedTopicRepository")
 */
class AllocatedTopic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $allocated_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $allocated_date;

    /**
     * @ORM\OneToOne(targetEntity="Student", inversedBy="alloctedTopic")
     * @ORM\JoinColumn(name="student_id", referencedColumnName="student_id")
     */
    private $student;

    /**
     * @ORM\OneToOne(targetEntity="Topic", inversedBy="allocated")
     * @ORM\JoinColumn(name="topic_id", referencedColumnName="topic_id")
     */
    private $topic;

    public function getAllocatedDate(): ?\DateTimeInterface
    {
        return $this->allocated_date;
    }

    public function setAllocatedDate(\DateTimeInterface $allocated_date): self
    {
        $this->allocated_date = $allocated_date;

        return $this;
    }

    public function getAllocatedId(): ?int
    {
        return $this->allocated_id;
    }

    public function getStudent(): ?Student
    {
        return $this->student;
    }

    public function setStudent(?Student $student): self
    {
        $this->student = $student;

        return $this;
    }

    public function getTopic(): ?Topic
    {
        return $this->topic;
    }

    public function setTopic(?Topic $topic): self
    {
        $this->topic = $topic;

        return $this;
    }
}

src/Entity/Student.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StudentRepository")
 * @UniqueEntity("matric_no", message="This Matric Number already exist!")
 * @UniqueEntity("email", message="This email address already exist!")
 */
class Student
{
    /**
     * @var integer
     * @ORM\Id()
     * @ORM\Column(name="student_id", type="integer", options={"unsigned": true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $student_id;

    /**
     * @ORM\OneToOne(targetEntity="AllocatedTopic", mappedBy="student")
     */
    private $alloctedTopic;

    /**
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @Assert\Length(min=9)
     * @ORM\Column(type="integer",length=9, unique=true,options={"unsigned": true})
     */
    private $matric_no;
    /**
     * @ORM\Column(type="string",length=20)
     * @Assert\NotBlank()
     * @Assert\NotNull()
     */
    private $first_name;
    /**
     * @Assert\NotNull()
     * @Assert\NotBlank()
     * @ORM\Column(type="string",length=20)
     */
    private $last_name;
    /**
     * @Assert\NotNull()
     * @Assert\NotBlank()
     * @Assert\Email()
     * @ORM\Column(type="string",length=50, unique=true)
     */
    private $email;
    /**
     * @Assert\Choice(
     *     choices={"2016/2017","2017/2018","2018/2019","2019/2020"},
     *     message="Select a valid session"
     * )
     * @ORM\Column(type="string",length=10)
     */
    private $session;
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @ORM\Column(type="string",length=50)
     */
    private $first_interest;
    /**
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @ORM\Column(type="string",length=50)
     */
    private $second_interest;
    /**
     * @var string
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @ORM\Column(type="string",length=50)
     */
    private $third_interest;
    /**
     * @ORM\GeneratedValue()
     * @ORM\Column(type="datetime")
     */
    private $registered;

    /**
     * @return int
     */
    public function getStudentId(): int
    {
        return $this->student_id;
    }

    /**
     * @param string $session
     */
    public function setSession(string $session): void
    {
        $this->session = $session;
    }

    /**
     * @return string
     */
    public function getSession(){
        return $this->session;
    }

    /**
     * @return \DateTime
     */
    public function getRegistered(): \DateTime
    {
        return $this->registered;
    }

    /**
     * @param \DateTime $registered
     */
    public function setRegistered(\DateTime $registered): void
    {
        $this->registered = $registered;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param string $last_name
     */
    public function setLastName(string $last_name): void
    {
        $this->last_name = $last_name;
    }

    /**
     * This method returns the matric number of a
     * student.
     * @return integer
     */
    public function getMatricNo(){
        return $this->matric_no;
    }

    /**
     * This method set the matric number of  a student.
     * @param int $matric_no
     */
    public function setMatricNo(int $matric_no){
        $this->matric_no = $matric_no;
    }

    /**
     * @return string
     */
    public function getFirstName():?string    {
        return $this->first_name;
    }

    /**
     * @param string  $first_name
     */
    public function setFirstName(string $first_name): void
    {
        $this->first_name = $first_name;
    }

    public function getAlloctedTopic(): ?AllocatedTopic
    {
        return $this->alloctedTopic;
    }

    public function setAlloctedTopic(?AllocatedTopic $alloctedTopic): self
    {
        $this->alloctedTopic = $alloctedTopic;

        // set (or unset) the owning side of the relation if necessary
        $newStudent = $alloctedTopic === null ? null : $this;
        if ($newStudent !== $alloctedTopic->getStudent()) {
            $alloctedTopic->setStudent($newStudent);
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSecondInterest()
    {
        return $this->second_interest;
    }

    /**
     * @param mixed $second_interest
     */
    public function setSecondInterest($second_interest): void
    {
        $this->second_interest = $second_interest;
    }

    /**
     * @return string
     */
    public function getFirstInterest()
    {
        return $this->first_interest;
    }

    /**
     * @param string $first_interest
     */
    public function setFirstInterest(string $first_interest): void
    {
        $this->first_interest = $first_interest;
    }

    /**
     * @return string
     */
    public function getThirdInterest()
    {
        return $this->third_interest;
    }

    /**
     * @param string $third_interest
     */
    public function setThirdInterest(string $third_interest): void
    {
        $this->third_interest = $third_interest;
    }
}

src/Entity/Supervisor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use \DateTime;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SupervisorRepository")
 * @UniqueEntity("phone_number")
 * @UniqueEntity("email")
 */
class Supervisor implements UserInterface,  \Serializable{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $supervisor_id;

    /**
     * @ORM\OneToMany(targetEntity="Topic", mappedBy="supervisor")
     */
    private $topics;

    /**
     * @ORM\Column(type="string", length=4)
     * @Assert\Choice(
     *     choices={"Prof","Dr","Mr"},
     *     message="Please select a valid title")
     */
    private $title;

    /**
     * @ORM\Column(type="string",length=30)
     * @var string
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @Assert\NotNull()
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=20)
     */
    private $first_name;

    /**
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @ORM\Column(type="string", length=20)
     */
    private $last_name;

    /**
     * @var string
     * @Assert\NotNull()
     * @Assert\NotBlank()
     * @Assert\Length(min=10,max=14)
     * @ORM\Column(type="string", length=14,unique=true)
     */
    private $phone_number;

    /**
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @Assert\Email()
     * @ORM\Column(type="string", length=50, unique=true)
     */
    private $email;

    /**
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @Assert\Length(min=8)
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @Assert\NotBlank()
     * @Assert\GreaterThan(value=0)
     * @Assert\NotNull()
     * @ORM\Column(type="integer", length=5)
     */
    private $capacity;

    /**
     * @ORM\GeneratedValue()
     * @var DateTime
     * @ORM\Column(type="datetime")
     */
    private $registered;

    public function __construct(){
        $this->topics = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getRegistered(): DateTime
    {
        return $this->registered;
    }

    /**
     * @param \DateTime $registered
     */
    public function setRegistered(DateTime $registered): void
    {
        $this->registered = $registered;
    }

    public function getRoles(){
        return ["ROLE_SUPERVISOR"];
    }

    /**
     * @return mixed
     */
    public function getCapacity()
    {
        return $this->capacity;
    }

    /**
     * @param int $capacity
     */
    public function setCapacity(int $capacity): void
    {
        $this->capacity = $capacity;
    }

    public function getSupervisorId(): ?int
    {
        return $this->supervisor_id;
    }

    public function setSupervisorId(int $supervisor_id): self
    {
        $this->supervisor_id = $supervisor_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = ucfirst($first_name);
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = ucfirst($last_name);

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * This
     * @param string $password
     * @return bool
     */
    public function isPasswordValid(string $password): bool {
        return password_verify($password,$this->password);
    }

    /**
     * This method return the
     * hashed password.
     * @return string
     */
    public function getHashedPassword(): string{
        return password_hash($this->password, PASSWORD_BCRYPT);
    }

    /**
     * @return Collection|Topic[]
     */
    public function getTopics(): Collection
    {
        return $this->topics;
    }

    public function addTopic(Topic $topic): self
    {
        if (!$this->topics->contains($topic)) {
            $this->topics[] = $topic;
            $topic->setSupervisor($this);
        }

        return $this;
    }

    public function removeTopic(Topic $topic): self
    {
        if ($this->topics->contains($topic)) {
            $this->topics->removeElement($topic);
            // set the owning side to null (unless already changed)
            if ($topic->getSupervisor() === $this) {
                $topic->setSupervisor(null);
            }
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getUsername()  {
        return $this->username;
    }

    /**
     * @param string $username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([$this->supervisor_id,$this->username,$this->email,$this->password]);
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list($this->supervisor_id,$this->username,
            $this->email,$this->password) = unserialize($serialized);
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Entity/Topic.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TopicRepository")
 * @UniqueEntity("name",message="This topic name already exist.")
 */
class Topic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $topic_id;

    /**
     * @ORM\ManyToOne(targetEntity="Supervisor", inversedBy="topics")
     * @ORM\JoinColumn(name="supervisor_id", referencedColumnName="supervisor_id")
     */
    private $supervisor;

    /**
     * @ORM\OneToOne(targetEntity="AllocatedTopic", mappedBy="topic")
     */
    private $allocated;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @Assert\NotNull()
     * @ORM\ManyToOne(targetEntity="Domain", inversedBy="topics")
     * @ORM\JoinColumn(name="domain_id", referencedColumnName="id")
     */
    private $domain;

    /**
     * @ORM\Column(type="datetime")
     */
    private $added_date;

    /**
     * Topic constructor.
     */
    public function __construct()
    {
        $this->added_date = new \DateTime("now");
    }

    /**
     * @return mixed
     */
    public function getTopicId()
    {
        return $this->topic_id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = ucwords($name);

        return $this;
    }

    public function getAddedDate(): ?\DateTime
    {
        return $this->added_date;
    }

    public function setAddedDate(\DateTime $added_date): self
    {
        $this->added_date = $added_date;

        return $this;
    }
    public function getDomain(): ?Domain
    {
        return $this->domain;
    }

    public function setDomain(?Domain $domain): self
    {
        $this->domain = $domain;

        return $this;
    }

    public function getSupervisor(): ?Supervisor
    {
        return $this->supervisor;
    }

    public function setSupervisor(?Supervisor $supervisor): self
    {
        $this->supervisor = $supervisor;

        return $this;
    }

    public function getAllocated(): ?AllocatedTopic
    {
        return $this->allocated;
    }

    public function setAllocated(?AllocatedTopic $allocated): self
    {
        $this->allocated = $allocated;

        // set (or unset) the owning side of the relation if necessary
        $newTopic = $allocated === null ? null : $this;
        if ($newTopic !== $allocated->getTopic()) {
            $allocated->setTopic($newTopic);
        }

        return $this;
    }
}

templates/layout/admin/add_domain.html.twig
{% extends "base.html.twig" %}
{% block title %}Admin - Add Research Domain{% endblock %}
{% block body %}
	<div class="main-content">
		<!--left-fixed -navigation-->
		<div class=" sidebar" role="navigation">
            <div class="navbar-collapse">
				<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{{ path('admin_dashboard') }}"><i class="fa fa-dashboard nav_icon"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ path('admin_view_topics') }}"><i class="fa fa-bookmark nav_icon"></i>View Topics</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_allocate') }}" ><i class="fa fa-bookmark nav_icon"></i>Allocate Topics</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_research_domain') }}" class="active"><i class="fa fa-plus nav_icon"></i>Add Research Domain</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_view_students') }}"><i class="fa fa-users nav_icon"></i>View Students</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_view_supervisors') }}"><i class="fa fa-user nav_icon"></i>View Supervisors</a>
                        </li>
                        <li>
                            <a href="{{ path('logout') }}" style="color: red;"><i class="fa fa-sign-out nav_icon"></i>Logout</a>
                        </li>
                    </ul>
					<!-- //sidebar-collapse -->
				</nav>
			</div>
		</div>
		<!--left-fixed -navigation-->
		<!-- header-starts -->
		<div class="sticky-header header-section ">
			<div class="header-left">
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars"></i></button>
				<!--toggle button end-->
				<!--logo -->
				<div class="logo">
                    <a href="{{ path('admin_dashboard') }}">
                        <h1>UNDERGRADUATE PROJECT </h1>
                        <span>TOPICS ALLOCATION SYSTEM</span>
                    </a>
				</div>
				<!--//logo-->
				<div class="clearfix"> </div>
			</div>
			<div class="header-right">
			<!--notification menu end -->
				<div class="profile_details">		
					<ul>
						<li class="dropdown profile_details_drop">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<div class="profile_img">	
									<span class="prfil-img"><img src="{{ asset('img/favicon/apple-icon-60x60.png') }}" alt="logo"> </span>
							
								</div>	
							</a>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>				
			</div>
			<div class="clearfix"> </div>	
		</div>
		<!-- //header-ends -->
		<!-- main content start-->
        <style>
            .form-body .table ul li, .title1 .form-grids .form-title h5{
                font-size: small;
                color: red;
            }
        </style>
		<div id="page-wrapper">
			<div class="main-page">
			<h3 class="title1" style="color: #F2B33F;">Edit Topic</h3>
					<div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
						<div class="form-title">
							<h4>Edit project topic below:</h4>
                            {% if added %}
                                <div class="alert-success text-center" style="padding: 1em;">
                                   Research domain added successfully!
                                </div>
                            {% endif %}
						</div>

						<div class="form-body">
                            {{ form_start(form) }}
                                <table class="table table-responsive">
                                    <tr>
                                        <td>
                                            {{ form_row(form.name) }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <button style="width:100%;" type="submit" id="update" class="btn btn-primary" >
                                                <span class="fa fa-save"></span> Save
                                            </button>
                                        </td>
                                    </tr>
                                </table>
                            {{ form_end(form) }}
						</div>
					</div>
			
			
				<div class="clearfix"> </div>
			</div>
		</div>
		<!--footer-->
		<div class="footer">
		   <p>&copy; 2018 | CSC Dept. AAUA. </p>
		</div>
        <!--//footer-->
	</div>
    {% endblock %}

    {% block javascripts %}
        <!-- Classie -->
        <script src="{{ asset('control_panel/js/classie.js') }}"></script>
        <script>
            let update = document.getElementById('update');
            update.onclick = function(){
                document.getElementById('student_registration_matric_no').disabled = false;
            }
            var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
                showLeftPush = document.getElementById( 'showLeftPush' ),
                body = document.body;

            showLeftPush.onclick = function() {
                classie.toggle( this, 'active' );
                classie.toggle( body, 'cbp-spmenu-push-toright' );
                classie.toggle( menuLeft, 'cbp-spmenu-open' );
                disableOther( 'showLeftPush' );
            };


            function disableOther( button ) {
                if( button !== 'showLeftPush' ) {
                    classie.toggle( showLeftPush, 'disabled' );
                }
            }
        </script>
        <!--scrolling js-->
        <script src="{{ asset('control_panel/js/jquery.nicescroll.js') }}"></script>
        <script src="{{ asset('control_panel/js/scripts.js') }}"></script>
        <!--//scrolling js-->
        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('control_panel/js/bootstrap.js') }}"> </script>
    {% endblock %}

templates/layout/admin/view_students.html.twig
{% extends "base.html.twig" %}
{% block title %}Admin - View Students{% endblock %}
{% block body %}
	<div class="main-content">
		<!--left-fixed -navigation-->
		<div class=" sidebar" role="navigation">
            <div class="navbar-collapse">
				<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{{ path('admin_dashboard') }}"><i class="fa fa-dashboard nav_icon"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ path('admin_view_topics') }}"><i class="fa fa-bookmark nav_icon"></i>View Topics</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_allocate') }}" ><i class="fa fa-bookmark nav_icon"></i>Allocate Topics</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_research_domain') }}" ><i class="fa fa-list nav_icon"></i>Add Research Domain</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_view_students') }}" class="active"><i class="fa fa-users nav_icon"></i>View Students</a>
                            <!-- /nav-second-level -->
                        </li>
                        <li>
                            <a href="{{ path('admin_view_supervisors') }}"><i class="fa fa-user nav_icon"></i>View Supervisors</a>
                        </li>
                        <li>
                            <a href="{{ path('logout') }}" style="color: red;"><i class="fa fa-sign-out nav_icon"></i>Logout</a>
                        </li>
                    </ul>
					<!-- //sidebar-collapse -->
				</nav>
			</div>
		</div>
		<!--left-fixed -navigation-->
		<!-- header-starts -->
		<div class="sticky-header header-section ">
			<div class="header-left">
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars"></i></button>
				<!--toggle button end-->
				<!--logo -->
				<div class="logo">
                    <a href="{{ path('admin_dashboard') }}">
                        <h1>UNDERGRADUATE PROJECT </h1>
                        <span>TOPICS ALLOCATION SYSTEM</span>
                    </a>
				</div>
				<!--//logo-->
				<div class="clearfix"> </div>
			</div>
			<div class="header-right">
			<!--notification menu end -->
				<div class="profile_details">		
					<ul>
						<li class="dropdown profile_details_drop">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<div class="profile_img">	
									<span class="prfil-img"><img src="{{ asset('img/favicon/apple-icon-60x60.png') }}" alt="logo"> </span>
							
								</div>	
							</a>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>				
			</div>
			<div class="clearfix"> </div>	
		</div>
		<!-- //header-ends -->
		<!-- main content start-->
        <style>
            .form-body .table ul li, .title1 .form-grids .form-title h5{
                font-size: small;
                color: red;
            }
        </style>
		<div id="page-wrapper">
			<div class="main-page">
			<h3 class="title1" style="color: #F2B33F;">View Students</h3>
					<div class="form-grids row widget-shadow" data-example-id="basic-forms"> 
						<div class="form-title">
							<h4>List of registered students</h4>

						</div>
						<div class="form-body">
                                <table class="table table-responsive table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Matric Number</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Email</th>
                                            <th>Research Interest</th>
                                            <th>Registered</th>
                                        </tr>
                                    </thead>
                                    {% set i = 0 %}
                                    {% for student in students %}
                                        <tbody>
                                            <tr>
                                                <td>
                                                    {% set i = i+1 %}
                                                    {{ i }}
                                                </td>
                                                <td>
                                                    {{ student.matricNo }}
                                                </td>
                                                <td>
                                                    {{ student.firstName }}
                                                </td>
                                                <td>
                                                    {{ student.lastName}}
                                                </td>
                                                <td>
                                                    {{ student.email }}
                                                </td>
                                                <td>
                                                    {{ student.firstInterest}},{{ student.secondInterest}},
                                                    {{ student.thirdInterest}}
                                                </td>
                                                <td>
                                                    {{ student.registered.format("d-M-Y") }}
                                                </td>
                                            </tr>
                                        </tbody>
                                    {% endfor %}
                                </table>
						</div>
					</div>
			
			
				<div class="clearfix"> </div>
			</div>
		</div>
		<!--footer-->
		<div class="footer">
		   <p>&copy; 2018 | CSC Dept. AAUA. </p>
		</div>
        <!--//footer-->
	</div>
    {% endblock %}

    {% block javascripts %}
        <!-- Classie -->
        <script src="{{ asset('control_panel/js/classie.js') }}"></script>
        <script>
            let update = document.getElementById('update');
            update.onclick = function(){
                document.getElementById('student_registration_matric_no').disabled = false;
            }
            var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
                showLeftPush = document.getElementById( 'showLeftPush' ),
                body = document.body;

            showLeftPush.onclick = function() {
                classie.toggle( this, 'active' );
                classie.toggle( body, 'cbp-spmenu-push-toright' );
                classie.toggle( menuLeft, 'cbp-spmenu-open' );
                disableOther( 'showLeftPush' );
            };


            function disableOther( button ) {
                if( button !== 'showLeftPush' ) {
                    classie.toggle( showLeftPush, 'disabled' );
                }
            }
        </script>
        <!--scrolling js-->
        <script src="{{ asset('control_panel/js/jquery.nicescroll.js') }}"></script>
        <script src="{{ asset('control_panel/js/scripts.js') }}"></script>
        <!--//scrolling js-->
        <!-- Bootstrap Core JavaScript -->
        <script src="{{ asset('control_panel/js/bootstrap.js') }}"> </script>
    {% endblock %}